export const DASHBOARD_PERMISSIONS = {
  VIEW_MENU: 'DASHBOARD_VIEW_MENU',
  VIEW_KPIS: 'DASHBOARD_VIEW_KPIS',
  VIEW_CHARTS: 'DASHBOARD_VIEW_CHARTS',
  VIEW_OPERATIONAL_KPIS: 'DASHBOARD_VIEW_OPERATIONAL_KPIS',
  VIEW_RECENT_QUOTES: 'DASHBOARD_VIEW_RECENT_QUOTES',
  VIEW_RECENT_ORDERS: 'DASHBOARD_VIEW_RECENT_ORDERS',
  VIEW_NEW_PATIENTS: 'DASHBOARD_VIEW_NEW_PATIENTS',
  APPLY_FILTERS: 'DASHBOARD_APPLY_FILTERS',
} as const;

export type DashboardPermission = (typeof DASHBOARD_PERMISSIONS)[keyof typeof DASHBOARD_PERMISSIONS];

export const ALERT_CENTER_PERMISSIONS = {
  VIEW_MENU: 'ALERT_CENTER_VIEW_MENU',
  VIEW_LIST: 'ALERT_CENTER_VIEW_LIST',
  VIEW_KPIS: 'ALERT_CENTER_VIEW_KPIS',
  VIEW_DETAIL: 'ALERT_CENTER_VIEW_DETAIL',
  SEND_EMAIL: 'ALERT_CENTER_SEND_EMAIL',
  SEND_SMS: 'ALERT_CENTER_SEND_SMS',
  SEND_WHATSAPP: 'ALERT_CENTER_SEND_WHATSAPP',
  REGISTER_CALL: 'ALERT_CENTER_REGISTER_CALL',
  COMPLETE: 'ALERT_CENTER_COMPLETE',
  SNOOZE: 'ALERT_CENTER_SNOOZE',
  IGNORE: 'ALERT_CENTER_IGNORE',
  ASSIGN: 'ALERT_CENTER_ASSIGN',
  ADD_NOTES: 'ALERT_CENTER_ADD_NOTES',
  PRINT: 'ALERT_CENTER_PRINT',
  BULK_ACTIONS: 'ALERT_CENTER_BULK_ACTIONS',
  FILTER: 'ALERT_CENTER_FILTER',
} as const;

export type AlertCenterPermission = (typeof ALERT_CENTER_PERMISSIONS)[keyof typeof ALERT_CENTER_PERMISSIONS];

export const CASHIER_PERMISSIONS = {
  VIEW_MENU: 'CASHIER_VIEW_MENU',
  VIEW_WIDGET: 'CASHIER_VIEW_WIDGET',
  CASH_SESSION_VIEW_LIST: 'CASH_SESSION_VIEW_LIST',
  CASH_SESSION_OPEN: 'CASH_SESSION_OPEN',
  CASH_SESSION_SET_EXCHANGE_RATE: 'CASH_SESSION_SET_EXCHANGE_RATE',
  CASH_SESSION_COUNT_OPENING: 'CASH_SESSION_COUNT_OPENING',
  CASH_SESSION_FILL_LAST_CLOSE: 'CASH_SESSION_FILL_LAST_CLOSE',
  CASH_SESSION_PRINT_OPENING: 'CASH_SESSION_PRINT_OPENING',
  CASH_SESSION_VIEW_DETAIL: 'CASH_SESSION_VIEW_DETAIL',
  CASH_SESSION_VIEW_TRANSACTIONS: 'CASH_SESSION_VIEW_TRANSACTIONS',
  CASH_SESSION_CLOSE_REVIEW: 'CASH_SESSION_CLOSE_REVIEW',
  CASH_SESSION_CLOSE_COUNT: 'CASH_SESSION_CLOSE_COUNT',
  CASH_SESSION_CLOSE_DEPOSIT: 'CASH_SESSION_CLOSE_DEPOSIT',
  CASH_SESSION_CLOSE_DECLARE: 'CASH_SESSION_CLOSE_DECLARE',
  CASH_SESSION_CLOSE_JUSTIFY: 'CASH_SESSION_CLOSE_JUSTIFY',
  CASH_SESSION_CLOSE_CONFIRM: 'CASH_SESSION_CLOSE_CONFIRM',
  CASH_SESSION_PRINT_CLOSE: 'CASH_SESSION_PRINT_CLOSE',
  CASH_SESSION_REPRINT: 'CASH_SESSION_REPRINT',
  CASH_REGISTER_VIEW_MENU: 'CASH_REGISTER_VIEW_MENU',
  CASH_REGISTER_VIEW_LIST: 'CASH_REGISTER_VIEW_LIST',
  CASH_REGISTER_CREATE: 'CASH_REGISTER_CREATE',
  CASH_REGISTER_UPDATE: 'CASH_REGISTER_UPDATE',
  CASH_REGISTER_TOGGLE_STATUS: 'CASH_REGISTER_TOGGLE_STATUS',
  MISC_TRANSACTION_VIEW_MENU: 'MISC_TRANSACTION_VIEW_MENU',
  MISC_TRANSACTION_VIEW_LIST: 'MISC_TRANSACTION_VIEW_LIST',
  MISC_TRANSACTION_CREATE: 'MISC_TRANSACTION_CREATE',
  MISC_TRANSACTION_UPDATE: 'MISC_TRANSACTION_UPDATE',
  MISC_TRANSACTION_DELETE: 'MISC_TRANSACTION_DELETE',
} as const;

export type CashierPermission = (typeof CASHIER_PERMISSIONS)[keyof typeof CASHIER_PERMISSIONS];

export const PATIENTS_PERMISSIONS = {
  // Menu
  VIEW_MENU: 'PATIENTS_VIEW_MENU',
  // Patient List
  VIEW_LIST: 'PATIENTS_VIEW_LIST',
  CREATE: 'PATIENTS_CREATE',
  UPDATE: 'PATIENTS_UPDATE',
  TOGGLE_STATUS: 'PATIENTS_TOGGLE_STATUS',
  SEARCH_DEBTORS: 'PATIENTS_SEARCH_DEBTORS',
  COPY_ID: 'PATIENTS_COPY_ID',
  // Patient Detail Panel
  VIEW_DETAIL: 'PATIENTS_VIEW_DETAIL',
  VIEW_DETAIL_HISTORY: 'PATIENTS_VIEW_DETAIL_HISTORY',
  VIEW_DETAIL_APPOINTMENTS: 'PATIENTS_VIEW_DETAIL_APPOINTMENTS',
  VIEW_DETAIL_QUOTES: 'PATIENTS_VIEW_DETAIL_QUOTES',
  VIEW_DETAIL_ORDERS: 'PATIENTS_VIEW_DETAIL_ORDERS',
  VIEW_DETAIL_INVOICES: 'PATIENTS_VIEW_DETAIL_INVOICES',
  VIEW_DETAIL_PAYMENTS: 'PATIENTS_VIEW_DETAIL_PAYMENTS',
  VIEW_DETAIL_MESSAGES: 'PATIENTS_VIEW_DETAIL_MESSAGES',
  VIEW_DETAIL_NOTES: 'PATIENTS_VIEW_DETAIL_NOTES',
  // Notes
  CREATE_NOTE: 'PATIENTS_CREATE_NOTE',
  UPDATE_NOTE: 'PATIENTS_UPDATE_NOTE',
  DELETE_NOTE: 'PATIENTS_DELETE_NOTE',
} as const;

export type PatientsPermission = (typeof PATIENTS_PERMISSIONS)[keyof typeof PATIENTS_PERMISSIONS];

export const MEDICAL_HISTORY_PERMISSIONS = {
  VIEW_MENU: 'MEDICAL_HISTORY_VIEW_MENU',
  VIEW: 'MEDICAL_HISTORY_VIEW',
} as const;

export type MedicalHistoryPermission = (typeof MEDICAL_HISTORY_PERMISSIONS)[keyof typeof MEDICAL_HISTORY_PERMISSIONS];

export const ANAMNESIS_PERMISSIONS = {
  VIEW: 'ANAMNESIS_VIEW',
  ADD_PERSONAL: 'ANAMNESIS_ADD_PERSONAL',
  DELETE_PERSONAL: 'ANAMNESIS_DELETE_PERSONAL',
  ADD_FAMILY: 'ANAMNESIS_ADD_FAMILY',
  DELETE_FAMILY: 'ANAMNESIS_DELETE_FAMILY',
  ADD_ALLERGY: 'ANAMNESIS_ADD_ALLERGY',
  DELETE_ALLERGY: 'ANAMNESIS_DELETE_ALLERGY',
  ADD_MEDICATION: 'ANAMNESIS_ADD_MEDICATION',
  DELETE_MEDICATION: 'ANAMNESIS_DELETE_MEDICATION',
  UPDATE_HABITS: 'ANAMNESIS_UPDATE_HABITS',
} as const;

export type AnamnesisPermission = (typeof ANAMNESIS_PERMISSIONS)[keyof typeof ANAMNESIS_PERMISSIONS];

export const TIMELINE_PERMISSIONS = {
  VIEW: 'TIMELINE_VIEW',
  CREATE: 'CLINICAL_SESSION_CREATE',
  VIEW_DETAIL: 'CLINICAL_SESSION_VIEW_DETAIL',
  UPDATE: 'CLINICAL_SESSION_UPDATE',
  DELETE: 'CLINICAL_SESSION_DELETE',
  UPLOAD_ATTACHMENT: 'CLINICAL_SESSION_UPLOAD_ATTACHMENT',
  VIEW_ATTACHMENTS: 'CLINICAL_SESSION_VIEW_ATTACHMENTS',
  DELETE_ATTACHMENT: 'CLINICAL_SESSION_DELETE_ATTACHMENT',
} as const;

export type TimelinePermission = (typeof TIMELINE_PERMISSIONS)[keyof typeof TIMELINE_PERMISSIONS];

export const ODONTOGRAM_PERMISSIONS = {
  VIEW: 'ODONTOGRAM_VIEW',
  NAVIGATE_HISTORY: 'ODONTOGRAM_NAVIGATE_HISTORY',
  START_SESSION: 'ODONTOGRAM_START_SESSION',
  MARK_CONDITIONS: 'ODONTOGRAM_MARK_CONDITIONS',
  CLEAR: 'ODONTOGRAM_CLEAR',
  REGISTER_SESSION: 'ODONTOGRAM_REGISTER_SESSION',
  TOGGLE_VIEW: 'ODONTOGRAM_TOGGLE_VIEW',
  UPLOAD_IMAGES: 'ODONTOGRAM_UPLOAD_IMAGES',
} as const;

export type OdontogramPermission = (typeof ODONTOGRAM_PERMISSIONS)[keyof typeof ODONTOGRAM_PERMISSIONS];

export const CLINICAL_DOCS_PERMISSIONS = {
  VIEW: 'CLINICAL_DOCS_VIEW',
  UPLOAD: 'CLINICAL_DOCS_UPLOAD',
  DELETE: 'CLINICAL_DOCS_DELETE',
  VIEW_ADVANCED: 'CLINICAL_DOCS_VIEW_ADVANCED',
} as const;

export type ClinicalDocsPermission = (typeof CLINICAL_DOCS_PERMISSIONS)[keyof typeof CLINICAL_DOCS_PERMISSIONS];

export const DICOM_PERMISSIONS = {
  VIEW_MENU: 'DICOM_VIEW_MENU',
  VIEW_LIST: 'DICOM_VIEW_LIST',
  VIEW_STUDY: 'DICOM_VIEW_STUDY',
  USE_MPR: 'DICOM_USE_MPR',
  USE_MEASUREMENTS: 'DICOM_USE_MEASUREMENTS',
  USE_WINDOW: 'DICOM_USE_WINDOW',
  ADD_ANNOTATIONS: 'DICOM_ADD_ANNOTATIONS',
  CHANGE_LAYOUT: 'DICOM_CHANGE_LAYOUT',
} as const;

export type DicomPermission = (typeof DICOM_PERMISSIONS)[keyof typeof DICOM_PERMISSIONS];

// Sales Permissions
export const SALES_PERMISSIONS = {
  // Sales Menu
  VIEW_MENU: 'SALES_VIEW_MENU',

  // Quotes (Presupuestos)
  QUOTES_VIEW_MENU: 'SALES_QUOTES_VIEW_MENU',
  QUOTES_VIEW_LIST: 'SALES_QUOTES_VIEW_LIST',
  QUOTES_CREATE: 'SALES_QUOTES_CREATE',
  QUOTES_UPDATE: 'SALES_QUOTES_UPDATE',
  QUOTES_DELETE: 'SALES_QUOTES_DELETE',
  QUOTES_CONFIRM: 'SALES_QUOTES_CONFIRM',
  QUOTES_REJECT: 'SALES_QUOTES_REJECT',
  QUOTES_SEND_EMAIL: 'SALES_QUOTES_SEND_EMAIL',
  QUOTES_PRINT: 'SALES_QUOTES_PRINT',
  QUOTES_VIEW_DETAIL: 'SALES_QUOTES_VIEW_DETAIL',

  // Quote Items (Presupuestos > Items)
  QUOTES_VIEW_ITEMS: 'SALES_QUOTES_VIEW_ITEMS',
  QUOTES_ADD_ITEM: 'SALES_QUOTES_ADD_ITEM',
  QUOTES_UPDATE_ITEM: 'SALES_QUOTES_UPDATE_ITEM',
  QUOTES_DELETE_ITEM: 'SALES_QUOTES_DELETE_ITEM',

  // Quote Orders (Presupuestos > Órdenes)
  QUOTES_VIEW_ORDERS: 'SALES_QUOTES_VIEW_ORDERS',

  // Quote Invoices (Presupuestos > Facturas)
  QUOTES_VIEW_INVOICES: 'SALES_QUOTES_VIEW_INVOICES',

  // Quote Payments (Presupuestos > Pagos)
  QUOTES_VIEW_PAYMENTS: 'SALES_QUOTES_VIEW_PAYMENTS',

  // Orders (Órdenes de Venta)
  ORDERS_VIEW_MENU: 'SALES_ORDERS_VIEW_MENU',
  ORDERS_VIEW_LIST: 'SALES_ORDERS_VIEW_LIST',
  ORDERS_CREATE: 'SALES_ORDERS_CREATE',
  ORDERS_UPDATE: 'SALES_ORDERS_UPDATE',
  ORDERS_DELETE: 'SALES_ORDERS_DELETE',
  ORDERS_VIEW_DETAIL: 'SALES_ORDERS_VIEW_DETAIL',

  // Order Items (Órdenes > Items)
  ORDERS_VIEW_ITEMS: 'SALES_ORDERS_VIEW_ITEMS',
  ORDERS_ADD_ITEM: 'SALES_ORDERS_ADD_ITEM',
  ORDERS_UPDATE_ITEM: 'SALES_ORDERS_UPDATE_ITEM',
  ORDERS_DELETE_ITEM: 'SALES_ORDERS_DELETE_ITEM',
  ORDERS_SCHEDULE_ITEM: 'SALES_ORDERS_SCHEDULE_ITEM',
  ORDERS_COMPLETE_ITEM: 'SALES_ORDERS_COMPLETE_ITEM',
  ORDERS_INVOICE_FROM_ORDER: 'SALES_ORDERS_INVOICE_FROM_ORDER',

  // Invoices (Facturas)
  INVOICES_VIEW_MENU: 'SALES_INVOICES_VIEW_MENU',
  INVOICES_VIEW_LIST: 'SALES_INVOICES_VIEW_LIST',
  INVOICES_CREATE: 'SALES_INVOICES_CREATE',
  INVOICES_UPDATE: 'SALES_INVOICES_UPDATE',
  INVOICES_DELETE: 'SALES_INVOICES_DELETE',
  INVOICES_CONFIRM: 'SALES_INVOICES_CONFIRM',
  INVOICES_VIEW_DETAIL: 'SALES_INVOICES_VIEW_DETAIL',
  INVOICES_PRINT: 'SALES_INVOICES_PRINT',
  INVOICES_SEND_EMAIL: 'SALES_INVOICES_SEND_EMAIL',

  // Invoice Items (Facturas > Items)
  INVOICES_VIEW_ITEMS: 'SALES_INVOICES_VIEW_ITEMS',
  INVOICES_ADD_ITEM: 'SALES_INVOICES_ADD_ITEM',
  INVOICES_UPDATE_ITEM: 'SALES_INVOICES_UPDATE_ITEM',
  INVOICES_DELETE_ITEM: 'SALES_INVOICES_DELETE_ITEM',

  // Credit Notes (Notas de Crédito)
  CREDIT_NOTE_CREATE: 'CREDIT_NOTE_CREATE',
  CREDIT_NOTE_VIEW_LIST: 'CREDIT_NOTE_VIEW_LIST',
  CREDIT_NOTE_CONFIRM: 'CREDIT_NOTE_CONFIRM',
  CREDIT_NOTE_SELECT_ITEMS: 'CREDIT_NOTE_SELECT_ITEMS',

  // Payments (Pagos)
  PAYMENTS_VIEW_MENU: 'SALES_PAYMENTS_VIEW_MENU',
  PAYMENTS_VIEW_LIST: 'SALES_PAYMENTS_VIEW_LIST',
  PAYMENTS_CREATE: 'SALES_PAYMENTS_CREATE',
  PAYMENTS_USE_CREDITS: 'SALES_PAYMENTS_USE_CREDITS',
  PAYMENTS_VIEW_DETAIL: 'SALES_PAYMENTS_VIEW_DETAIL',

  // Prepayments (Prepagos)
  PREPAYMENTS_CREATE: 'SALES_PREPAYMENTS_CREATE',
  PREPAYMENTS_VIEW: 'SALES_PREPAYMENTS_VIEW',

  // Payment Methods (Métodos de Pago)
  PAYMENT_METHODS_VIEW_MENU: 'PAYMENT_METHODS_VIEW_MENU',
  PAYMENT_METHODS_VIEW_LIST: 'PAYMENT_METHODS_VIEW_LIST',
  PAYMENT_METHODS_CREATE: 'PAYMENT_METHODS_CREATE',
  PAYMENT_METHODS_UPDATE: 'PAYMENT_METHODS_UPDATE',
  PAYMENT_METHODS_DELETE: 'PAYMENT_METHODS_DELETE',
  PAYMENT_METHODS_TOGGLE_STATUS: 'PAYMENT_METHODS_TOGGLE_STATUS',

  // Services (Servicios)
  SERVICES_VIEW_MENU: 'SALES_SERVICES_VIEW_MENU',
  SERVICES_VIEW_LIST: 'SALES_SERVICES_VIEW_LIST',
  SERVICES_CREATE: 'SALES_SERVICES_CREATE',
  SERVICES_UPDATE: 'SALES_SERVICES_UPDATE',
  SERVICES_DELETE: 'SALES_SERVICES_DELETE',
} as const;

export type SalesPermission = (typeof SALES_PERMISSIONS)[keyof typeof SALES_PERMISSIONS];

// Purchases Permissions
export const PURCHASES_PERMISSIONS = {
  // Purchases Menu
  VIEW_MENU: 'PURCHASES_VIEW_MENU',

  // Purchase Invoices (Facturas de Compra)
  INVOICES_VIEW_MENU: 'PURCHASE_INVOICES_VIEW_MENU',
  INVOICES_VIEW_LIST: 'PURCHASE_INVOICES_VIEW_LIST',
  INVOICES_CREATE: 'PURCHASE_INVOICES_CREATE',
  INVOICES_UPDATE: 'PURCHASE_INVOICES_UPDATE',
  INVOICES_DELETE: 'PURCHASE_INVOICES_DELETE',
  INVOICES_CONFIRM: 'PURCHASE_INVOICES_CONFIRM',
  INVOICES_IMPORT_AI: 'PURCHASE_INVOICES_IMPORT_AI',
  INVOICES_VIEW_DETAIL: 'PURCHASE_INVOICES_VIEW_DETAIL',

  // Invoice Items (Facturas Compra > Items)
  INVOICES_VIEW_ITEMS: 'PURCHASE_INVOICES_VIEW_ITEMS',
  INVOICES_ADD_ITEM: 'PURCHASE_INVOICES_ADD_ITEM',
  INVOICES_UPDATE_ITEM: 'PURCHASE_INVOICES_UPDATE_ITEM',
  INVOICES_DELETE_ITEM: 'PURCHASE_INVOICES_DELETE_ITEM',

  // Suppliers (Proveedores)
  SUPPLIERS_VIEW_MENU: 'SUPPLIERS_VIEW_MENU',
  SUPPLIERS_VIEW_LIST: 'SUPPLIERS_VIEW_LIST',
  SUPPLIERS_CREATE: 'SUPPLIERS_CREATE',
  SUPPLIERS_UPDATE: 'SUPPLIERS_UPDATE',
  SUPPLIERS_DELETE: 'SUPPLIERS_DELETE',
  SUPPLIERS_TOGGLE_STATUS: 'SUPPLIERS_TOGGLE_STATUS',
  SUPPLIERS_VIEW_DETAIL: 'SUPPLIERS_VIEW_DETAIL',

  // Supplier Services (Proveedores > Servicios)
  SUPPLIERS_VIEW_SERVICES: 'SUPPLIERS_VIEW_SERVICES',
  SUPPLIERS_ADD_SERVICE: 'SUPPLIERS_ADD_SERVICE',
  SUPPLIERS_UPDATE_SERVICE: 'SUPPLIERS_UPDATE_SERVICE',
  SUPPLIERS_DELETE_SERVICE: 'SUPPLIERS_DELETE_SERVICE',

  // Purchase Products (Productos y Servicios)
  PRODUCTS_VIEW_MENU: 'PURCHASE_PRODUCTS_VIEW_MENU',
  PRODUCTS_VIEW_LIST: 'PURCHASE_PRODUCTS_VIEW_LIST',
  PRODUCTS_CREATE: 'PURCHASE_PRODUCTS_CREATE',
  PRODUCTS_UPDATE: 'PURCHASE_PRODUCTS_UPDATE',
  PRODUCTS_DELETE: 'PURCHASE_PRODUCTS_DELETE',

  // Purchase Quotes (Presupuestos de Compra)
  QUOTES_VIEW_MENU: 'PURCHASE_QUOTES_VIEW_MENU',
  QUOTES_VIEW_LIST: 'PURCHASE_QUOTES_VIEW_LIST',
  QUOTES_CREATE: 'PURCHASE_QUOTES_CREATE',
  QUOTES_UPDATE: 'PURCHASE_QUOTES_UPDATE',
  QUOTES_DELETE: 'PURCHASE_QUOTES_DELETE',
  QUOTES_CONFIRM: 'PURCHASE_QUOTES_CONFIRM',

  // Purchase Orders (Órdenes de Compra)
  ORDERS_VIEW_MENU: 'PURCHASE_ORDERS_VIEW_MENU',
  ORDERS_VIEW_LIST: 'PURCHASE_ORDERS_VIEW_LIST',
  ORDERS_CREATE: 'PURCHASE_ORDERS_CREATE',
  ORDERS_UPDATE: 'PURCHASE_ORDERS_UPDATE',
  ORDERS_DELETE: 'PURCHASE_ORDERS_DELETE',
  ORDERS_CONVERT_INVOICE: 'PURCHASE_ORDERS_CONVERT_INVOICE',

  // Purchase Payments (Pagos a Proveedores)
  PAYMENTS_VIEW_MENU: 'PURCHASE_PAYMENTS_VIEW_MENU',
  PAYMENTS_VIEW_LIST: 'PURCHASE_PAYMENTS_VIEW_LIST',
  PAYMENTS_CREATE: 'PURCHASE_PAYMENTS_CREATE',
  PAYMENTS_VIEW_DETAIL: 'PURCHASE_PAYMENTS_VIEW_DETAIL',
} as const;

export type PurchasesPermission = (typeof PURCHASES_PERMISSIONS)[keyof typeof PURCHASES_PERMISSIONS];

// Clinic Catalog Permissions
export const CLINIC_CATALOG_PERMISSIONS = {
  // Catalog Menu
  VIEW_MENU: 'CATALOG_VIEW_MENU',

  // Ailments (Padecimientos)
  CONDITIONS_VIEW_MENU: 'CATALOG_CONDITIONS_VIEW_MENU',
  CONDITIONS_VIEW_LIST: 'CATALOG_CONDITIONS_VIEW_LIST',
  CONDITIONS_CREATE: 'CATALOG_CONDITIONS_CREATE',
  CONDITIONS_UPDATE: 'CATALOG_CONDITIONS_UPDATE',
  CONDITIONS_DELETE: 'CATALOG_CONDITIONS_DELETE',

  // Medications (Medicamentos)
  MEDICATIONS_VIEW_MENU: 'CATALOG_MEDICATIONS_VIEW_MENU',
  MEDICATIONS_VIEW_LIST: 'CATALOG_MEDICATIONS_VIEW_LIST',
  MEDICATIONS_CREATE: 'CATALOG_MEDICATIONS_CREATE',
  MEDICATIONS_UPDATE: 'CATALOG_MEDICATIONS_UPDATE',
  MEDICATIONS_DELETE: 'CATALOG_MEDICATIONS_DELETE',

  // Dental Conditions (Condiciones Dentales)
  DENTAL_COND_VIEW_MENU: 'CATALOG_DENTAL_COND_VIEW_MENU',
  DENTAL_COND_VIEW_LIST: 'CATALOG_DENTAL_COND_VIEW_LIST',
  DENTAL_COND_CREATE: 'CATALOG_DENTAL_COND_CREATE',
  DENTAL_COND_UPDATE: 'CATALOG_DENTAL_COND_UPDATE',
  DENTAL_COND_DELETE: 'CATALOG_DENTAL_COND_DELETE',

  // Dental Surfaces (Superficies Dentales)
  DENTAL_SURF_VIEW_MENU: 'CATALOG_DENTAL_SURF_VIEW_MENU',
  DENTAL_SURF_VIEW_LIST: 'CATALOG_DENTAL_SURF_VIEW_LIST',
  DENTAL_SURF_CREATE: 'CATALOG_DENTAL_SURF_CREATE',
  DENTAL_SURF_UPDATE: 'CATALOG_DENTAL_SURF_UPDATE',
  DENTAL_SURF_DELETE: 'CATALOG_DENTAL_SURF_DELETE',
} as const;

export type ClinicCatalogPermission = (typeof CLINIC_CATALOG_PERMISSIONS)[keyof typeof CLINIC_CATALOG_PERMISSIONS];

// Business Config (Configuración de Negocio) Permissions
export const BUSINESS_CONFIG_PERMISSIONS = {
  // Business Config Menu
  VIEW_MENU: 'BUSINESS_CONFIG_VIEW_MENU',

  // Clinic Details
  CLINIC_DETAILS_VIEW: 'CLINIC_DETAILS_VIEW',
  CLINIC_DETAILS_UPDATE: 'CLINIC_DETAILS_UPDATE',
  CLINIC_DETAILS_UPLOAD_LOGO: 'CLINIC_DETAILS_UPLOAD_LOGO',

  // Schedules (Horarios Generales)
  SCHEDULES_VIEW_MENU: 'SCHEDULES_VIEW_MENU',
  SCHEDULES_VIEW_LIST: 'SCHEDULES_VIEW_LIST',
  SCHEDULES_CREATE: 'SCHEDULES_CREATE',
  SCHEDULES_UPDATE: 'SCHEDULES_UPDATE',
  SCHEDULES_DELETE: 'SCHEDULES_DELETE',

  // Holidays (Feriados y Excepciones)
  HOLIDAYS_VIEW_MENU: 'HOLIDAYS_VIEW_MENU',
  HOLIDAYS_VIEW_LIST: 'HOLIDAYS_VIEW_LIST',
  HOLIDAYS_CREATE: 'HOLIDAYS_CREATE',
  HOLIDAYS_UPDATE: 'HOLIDAYS_UPDATE',
  HOLIDAYS_DELETE: 'HOLIDAYS_DELETE',

  // Calendars
  CALENDARS_VIEW_MENU: 'CALENDARS_VIEW_MENU',
  CALENDARS_VIEW_LIST: 'CALENDARS_VIEW_LIST',
  CALENDARS_CREATE: 'CALENDARS_CREATE',
  CALENDARS_UPDATE: 'CALENDARS_UPDATE',
  CALENDARS_DELETE: 'CALENDARS_DELETE',
  CALENDARS_TOGGLE_STATUS: 'CALENDARS_TOGGLE_STATUS',

  // Doctors (Gestión de Doctores)
  DOCTORS_VIEW_MENU: 'DOCTORS_VIEW_MENU',
  DOCTORS_VIEW_LIST: 'DOCTORS_VIEW_LIST',
  DOCTORS_CREATE: 'DOCTORS_CREATE',
  DOCTORS_UPDATE: 'DOCTORS_UPDATE',
  DOCTORS_TOGGLE_STATUS: 'DOCTORS_TOGGLE_STATUS',
  DOCTORS_COPY_ID: 'DOCTORS_COPY_ID',
  DOCTORS_VIEW_DETAIL: 'DOCTORS_VIEW_DETAIL',

  // Doctor Services (Doctores > Servicios)
  DOCTORS_VIEW_SERVICES: 'DOCTORS_VIEW_SERVICES',
  DOCTORS_ADD_SERVICE: 'DOCTORS_ADD_SERVICE',
  DOCTORS_UPDATE_SERVICE: 'DOCTORS_UPDATE_SERVICE',
  DOCTORS_DELETE_SERVICE: 'DOCTORS_DELETE_SERVICE',

  // Availability (Disponibilidad Médica)
  AVAILABILITY_VIEW_MENU: 'AVAILABILITY_VIEW_MENU',

  // Availability Rules (Disponibilidad > Reglas)
  AVAILABILITY_RULES_VIEW: 'AVAILABILITY_RULES_VIEW',
  AVAILABILITY_RULES_CREATE: 'AVAILABILITY_RULES_CREATE',
  AVAILABILITY_RULES_UPDATE: 'AVAILABILITY_RULES_UPDATE',
  AVAILABILITY_RULES_DELETE: 'AVAILABILITY_RULES_DELETE',

  // Availability Exceptions (Disponibilidad > Excepciones)
  AVAILABILITY_EXCEPTIONS_VIEW: 'AVAILABILITY_EXCEPTIONS_VIEW',
  AVAILABILITY_EXCEPTIONS_CREATE: 'AVAILABILITY_EXCEPTIONS_CREATE',
  AVAILABILITY_EXCEPTIONS_UPDATE: 'AVAILABILITY_EXCEPTIONS_UPDATE',
  AVAILABILITY_EXCEPTIONS_DELETE: 'AVAILABILITY_EXCEPTIONS_DELETE',

  // Currencies (Monedas y Tipos de Cambio)
  CURRENCIES_VIEW_MENU: 'CURRENCIES_VIEW_MENU',
  CURRENCIES_VIEW_LIST: 'CURRENCIES_VIEW_LIST',
  CURRENCIES_VIEW_DETAIL: 'CURRENCIES_VIEW_DETAIL',

  // Sequences (Secuencias de Documentos)
  SEQUENCES_VIEW_MENU: 'SEQUENCES_VIEW_MENU',
  SEQUENCES_VIEW_LIST: 'SEQUENCES_VIEW_LIST',
  SEQUENCES_CREATE: 'SEQUENCES_CREATE',
  SEQUENCES_UPDATE: 'SEQUENCES_UPDATE',
  SEQUENCES_DELETE: 'SEQUENCES_DELETE',

  // Mutual Societies (Sociedades Mutuales)
  MUTUAL_SOC_VIEW_MENU: 'MUTUAL_SOC_VIEW_MENU',
  MUTUAL_SOC_VIEW_LIST: 'MUTUAL_SOC_VIEW_LIST',
  MUTUAL_SOC_CREATE: 'MUTUAL_SOC_CREATE',
  MUTUAL_SOC_UPDATE: 'MUTUAL_SOC_UPDATE',
  MUTUAL_SOC_DELETE: 'MUTUAL_SOC_DELETE',
} as const;

export type BusinessConfigPermission = (typeof BUSINESS_CONFIG_PERMISSIONS)[keyof typeof BUSINESS_CONFIG_PERMISSIONS];

// Global (Panel Superior) Permissions
export const GLOBAL_PERMISSIONS = {
  // Profile
  PROFILE_CHANGE_PASSWORD: 'PROFILE_CHANGE_PASSWORD',

  // Panel Superior
  GLOBAL_CHANGE_LANGUAGE: 'GLOBAL_CHANGE_LANGUAGE',
  GLOBAL_CHANGE_THEME: 'GLOBAL_CHANGE_THEME',
  GLOBAL_VIEW_EXCHANGE_RATE: 'GLOBAL_VIEW_EXCHANGE_RATE',
  GLOBAL_VIEW_NOTIFICATIONS_BADGE: 'GLOBAL_VIEW_NOTIFICATIONS_BADGE',
} as const;

export type GlobalPermission = (typeof GLOBAL_PERMISSIONS)[keyof typeof GLOBAL_PERMISSIONS];

// System (Admin) Permissions
export const SYSTEM_PERMISSIONS = {
  // System Menu
  VIEW_MENU: 'SYSTEM_VIEW_MENU',

  // Users
  USERS_VIEW_MENU: 'USERS_VIEW_MENU',
  USERS_VIEW_LIST: 'USERS_VIEW_LIST',
  USERS_CREATE: 'USERS_CREATE',
  USERS_UPDATE: 'USERS_UPDATE',
  USERS_SET_INITIAL_PASSWORD: 'USERS_SET_INITIAL_PASSWORD',
  USERS_TOGGLE_STATUS: 'USERS_TOGGLE_STATUS',
  USERS_VIEW_DETAIL: 'USERS_VIEW_DETAIL',
  USERS_VIEW_ROLES: 'USERS_VIEW_ROLES',
  USERS_ASSIGN_ROLE: 'USERS_ASSIGN_ROLE',
  USERS_REMOVE_ROLE: 'USERS_REMOVE_ROLE',
  USERS_VIEW_LOGS: 'USERS_VIEW_LOGS',

  // Roles
  ROLES_VIEW_MENU: 'ROLES_VIEW_MENU',
  ROLES_VIEW_LIST: 'ROLES_VIEW_LIST',
  ROLES_CREATE: 'ROLES_CREATE',
  ROLES_UPDATE: 'ROLES_UPDATE',
  ROLES_DELETE: 'ROLES_DELETE',
  ROLES_VIEW_USERS: 'ROLES_VIEW_USERS',
  ROLES_ADD_USER: 'ROLES_ADD_USER',
  ROLES_REMOVE_USER: 'ROLES_REMOVE_USER',
  ROLES_VIEW_PERMISSIONS: 'ROLES_VIEW_PERMISSIONS',
  ROLES_ASSIGN_PERMISSION: 'ROLES_ASSIGN_PERMISSION',
  ROLES_REMOVE_PERMISSION: 'ROLES_REMOVE_PERMISSION',

  // Permissions
  PERMISSIONS_VIEW_MENU: 'PERMISSIONS_VIEW_MENU',
  PERMISSIONS_VIEW_LIST: 'PERMISSIONS_VIEW_LIST',
  PERMISSIONS_CREATE: 'PERMISSIONS_CREATE',
  PERMISSIONS_UPDATE: 'PERMISSIONS_UPDATE',
  PERMISSIONS_DELETE: 'PERMISSIONS_DELETE',
  PERMISSIONS_VIEW_IMPACT: 'PERMISSIONS_VIEW_IMPACT',

  // System Config
  SYS_CONFIG_VIEW_MENU: 'SYS_CONFIG_VIEW_MENU',
  SYS_CONFIG_VIEW_LIST: 'SYS_CONFIG_VIEW_LIST',
  SYS_CONFIG_CREATE: 'SYS_CONFIG_CREATE',
  SYS_CONFIG_UPDATE: 'SYS_CONFIG_UPDATE',
  SYS_CONFIG_DELETE: 'SYS_CONFIG_DELETE',

  // Audit Log
  AUDIT_LOG_VIEW_MENU: 'AUDIT_LOG_VIEW_MENU',
  AUDIT_LOG_VIEW_LIST: 'AUDIT_LOG_VIEW_LIST',
  AUDIT_LOG_VIEW_DETAIL: 'AUDIT_LOG_VIEW_DETAIL',

  // Access Log
  ACCESS_LOG_VIEW_MENU: 'ACCESS_LOG_VIEW_MENU',
  ACCESS_LOG_VIEW_LIST: 'ACCESS_LOG_VIEW_LIST',

  // Error Log
  ERROR_LOG_VIEW_MENU: 'ERROR_LOG_VIEW_MENU',
  ERROR_LOG_VIEW_LIST: 'ERROR_LOG_VIEW_LIST',

  // Alert Config
  ALERT_CONFIG_VIEW_MENU: 'ALERT_CONFIG_VIEW_MENU',
  ALERT_CONFIG_VIEW: 'ALERT_CONFIG_VIEW',
  ALERT_CONFIG_UPDATE: 'ALERT_CONFIG_UPDATE',

  // Alert Categories
  ALERT_CATEGORIES_VIEW_MENU: 'ALERT_CATEGORIES_VIEW_MENU',
  ALERT_CATEGORIES_VIEW_LIST: 'ALERT_CATEGORIES_VIEW_LIST',
  ALERT_CATEGORIES_CREATE: 'ALERT_CATEGORIES_CREATE',
  ALERT_CATEGORIES_UPDATE: 'ALERT_CATEGORIES_UPDATE',
  ALERT_CATEGORIES_DELETE: 'ALERT_CATEGORIES_DELETE',

  // Alert Rules
  ALERT_RULES_VIEW_MENU: 'ALERT_RULES_VIEW_MENU',
  ALERT_RULES_VIEW_LIST: 'ALERT_RULES_VIEW_LIST',
  ALERT_RULES_CREATE: 'ALERT_RULES_CREATE',
  ALERT_RULES_UPDATE: 'ALERT_RULES_UPDATE',
  ALERT_RULES_DELETE: 'ALERT_RULES_DELETE',
  ALERT_RULES_TOGGLE_STATUS: 'ALERT_RULES_TOGGLE_STATUS',

  // Alert Templates
  ALERT_TEMPLATES_VIEW_MENU: 'ALERT_TEMPLATES_VIEW_MENU',
  ALERT_TEMPLATES_VIEW_LIST: 'ALERT_TEMPLATES_VIEW_LIST',
  ALERT_TEMPLATES_CREATE: 'ALERT_TEMPLATES_CREATE',
  ALERT_TEMPLATES_UPDATE: 'ALERT_TEMPLATES_UPDATE',
  ALERT_TEMPLATES_DELETE: 'ALERT_TEMPLATES_DELETE',

  // Alert Executions
  ALERT_EXECUTIONS_VIEW_MENU: 'ALERT_EXECUTIONS_VIEW_MENU',
  ALERT_EXECUTIONS_VIEW_LIST: 'ALERT_EXECUTIONS_VIEW_LIST',
  ALERT_EXECUTIONS_VIEW_DETAIL: 'ALERT_EXECUTIONS_VIEW_DETAIL',

  // Alert History
  ALERT_HISTORY_VIEW_MENU: 'ALERT_HISTORY_VIEW_MENU',
  ALERT_HISTORY_VIEW_LIST: 'ALERT_HISTORY_VIEW_LIST',
  ALERT_HISTORY_VIEW_DETAIL: 'ALERT_HISTORY_VIEW_DETAIL',

  // Notification Settings
  NOTIFICATION_SETTINGS_VIEW_MENU: 'NOTIFICATION_SETTINGS_VIEW_MENU',
} as const;

export type SystemPermission = (typeof SYSTEM_PERMISSIONS)[keyof typeof SYSTEM_PERMISSIONS];
