export const DASHBOARD_PERMISSIONS = {
  VIEW_MENU: 'DASHBOARD_VIEW_MENU',
  VIEW_KPIS: 'DASHBOARD_VIEW_KPIS',
  VIEW_CHARTS: 'DASHBOARD_VIEW_CHARTS',
  VIEW_OPERATIONAL_KPIS: 'DASHBOARD_VIEW_OPERATIONAL_KPIS',
  VIEW_RECENT_QUOTES: 'DASHBOARD_VIEW_RECENT_QUOTES',
  VIEW_RECENT_ORDERS: 'DASHBOARD_VIEW_RECENT_ORDERS',
  VIEW_NEW_PATIENTS: 'DASHBOARD_VIEW_NEW_PATIENTS',
  APPLY_FILTERS: 'DASHBOARD_APPLY_FILTERS',
} as const;

export type DashboardPermission = (typeof DASHBOARD_PERMISSIONS)[keyof typeof DASHBOARD_PERMISSIONS];

export const ALERT_CENTER_PERMISSIONS = {
  VIEW_MENU: 'ALERT_CENTER_VIEW_MENU',
  VIEW_LIST: 'ALERT_CENTER_VIEW_LIST',
  VIEW_KPIS: 'ALERT_CENTER_VIEW_KPIS',
  VIEW_DETAIL: 'ALERT_CENTER_VIEW_DETAIL',
  SEND_EMAIL: 'ALERT_CENTER_SEND_EMAIL',
  SEND_SMS: 'ALERT_CENTER_SEND_SMS',
  SEND_WHATSAPP: 'ALERT_CENTER_SEND_WHATSAPP',
  REGISTER_CALL: 'ALERT_CENTER_REGISTER_CALL',
  COMPLETE: 'ALERT_CENTER_COMPLETE',
  SNOOZE: 'ALERT_CENTER_SNOOZE',
  IGNORE: 'ALERT_CENTER_IGNORE',
  ASSIGN: 'ALERT_CENTER_ASSIGN',
  ADD_NOTES: 'ALERT_CENTER_ADD_NOTES',
  PRINT: 'ALERT_CENTER_PRINT',
  BULK_ACTIONS: 'ALERT_CENTER_BULK_ACTIONS',
  FILTER: 'ALERT_CENTER_FILTER',
} as const;

export type AlertCenterPermission = (typeof ALERT_CENTER_PERMISSIONS)[keyof typeof ALERT_CENTER_PERMISSIONS];

export const CASHIER_PERMISSIONS = {
  VIEW_MENU: 'CASHIER_VIEW_MENU',
  VIEW_WIDGET: 'CASHIER_VIEW_WIDGET',
  CASH_SESSION_VIEW_LIST: 'CASH_SESSION_VIEW_LIST',
  CASH_SESSION_OPEN: 'CASH_SESSION_OPEN',
  CASH_SESSION_SET_EXCHANGE_RATE: 'CASH_SESSION_SET_EXCHANGE_RATE',
  CASH_SESSION_COUNT_OPENING: 'CASH_SESSION_COUNT_OPENING',
  CASH_SESSION_FILL_LAST_CLOSE: 'CASH_SESSION_FILL_LAST_CLOSE',
  CASH_SESSION_PRINT_OPENING: 'CASH_SESSION_PRINT_OPENING',
  CASH_SESSION_VIEW_DETAIL: 'CASH_SESSION_VIEW_DETAIL',
  CASH_SESSION_VIEW_TRANSACTIONS: 'CASH_SESSION_VIEW_TRANSACTIONS',
  CASH_SESSION_CLOSE_REVIEW: 'CASH_SESSION_CLOSE_REVIEW',
  CASH_SESSION_CLOSE_COUNT: 'CASH_SESSION_CLOSE_COUNT',
  CASH_SESSION_CLOSE_DEPOSIT: 'CASH_SESSION_CLOSE_DEPOSIT',
  CASH_SESSION_CLOSE_DECLARE: 'CASH_SESSION_CLOSE_DECLARE',
  CASH_SESSION_CLOSE_JUSTIFY: 'CASH_SESSION_CLOSE_JUSTIFY',
  CASH_SESSION_CLOSE_CONFIRM: 'CASH_SESSION_CLOSE_CONFIRM',
  CASH_SESSION_PRINT_CLOSE: 'CASH_SESSION_PRINT_CLOSE',
  CASH_SESSION_REPRINT: 'CASH_SESSION_REPRINT',
  CASH_REGISTER_VIEW_MENU: 'CASH_REGISTER_VIEW_MENU',
  CASH_REGISTER_VIEW_LIST: 'CASH_REGISTER_VIEW_LIST',
  CASH_REGISTER_CREATE: 'CASH_REGISTER_CREATE',
  CASH_REGISTER_UPDATE: 'CASH_REGISTER_UPDATE',
  CASH_REGISTER_TOGGLE_STATUS: 'CASH_REGISTER_TOGGLE_STATUS',
  MISC_TRANSACTION_VIEW_MENU: 'MISC_TRANSACTION_VIEW_MENU',
  MISC_TRANSACTION_VIEW_LIST: 'MISC_TRANSACTION_VIEW_LIST',
  MISC_TRANSACTION_CREATE: 'MISC_TRANSACTION_CREATE',
  MISC_TRANSACTION_UPDATE: 'MISC_TRANSACTION_UPDATE',
  MISC_TRANSACTION_DELETE: 'MISC_TRANSACTION_DELETE',
} as const;

export type CashierPermission = (typeof CASHIER_PERMISSIONS)[keyof typeof CASHIER_PERMISSIONS];

export const PATIENTS_PERMISSIONS = {
  // Menu
  VIEW_MENU: 'PATIENTS_VIEW_MENU',
  // Patient List
  VIEW_LIST: 'PATIENTS_VIEW_LIST',
  CREATE: 'PATIENTS_CREATE',
  UPDATE: 'PATIENTS_UPDATE',
  TOGGLE_STATUS: 'PATIENTS_TOGGLE_STATUS',
  SEARCH_DEBTORS: 'PATIENTS_SEARCH_DEBTORS',
  COPY_ID: 'PATIENTS_COPY_ID',
  // Patient Detail Panel
  VIEW_DETAIL: 'PATIENTS_VIEW_DETAIL',
  VIEW_DETAIL_HISTORY: 'PATIENTS_VIEW_DETAIL_HISTORY',
  VIEW_DETAIL_APPOINTMENTS: 'PATIENTS_VIEW_DETAIL_APPOINTMENTS',
  VIEW_DETAIL_QUOTES: 'PATIENTS_VIEW_DETAIL_QUOTES',
  VIEW_DETAIL_ORDERS: 'PATIENTS_VIEW_DETAIL_ORDERS',
  VIEW_DETAIL_INVOICES: 'PATIENTS_VIEW_DETAIL_INVOICES',
  VIEW_DETAIL_PAYMENTS: 'PATIENTS_VIEW_DETAIL_PAYMENTS',
  VIEW_DETAIL_MESSAGES: 'PATIENTS_VIEW_DETAIL_MESSAGES',
  VIEW_DETAIL_NOTES: 'PATIENTS_VIEW_DETAIL_NOTES',
  // Notes
  CREATE_NOTE: 'PATIENTS_CREATE_NOTE',
  UPDATE_NOTE: 'PATIENTS_UPDATE_NOTE',
  DELETE_NOTE: 'PATIENTS_DELETE_NOTE',
} as const;

export type PatientsPermission = (typeof PATIENTS_PERMISSIONS)[keyof typeof PATIENTS_PERMISSIONS];

export const MEDICAL_HISTORY_PERMISSIONS = {
  VIEW_MENU: 'MEDICAL_HISTORY_VIEW_MENU',
  VIEW: 'MEDICAL_HISTORY_VIEW',
} as const;

export type MedicalHistoryPermission = (typeof MEDICAL_HISTORY_PERMISSIONS)[keyof typeof MEDICAL_HISTORY_PERMISSIONS];

export const ANAMNESIS_PERMISSIONS = {
  VIEW: 'ANAMNESIS_VIEW',
  ADD_PERSONAL: 'ANAMNESIS_ADD_PERSONAL',
  DELETE_PERSONAL: 'ANAMNESIS_DELETE_PERSONAL',
  ADD_FAMILY: 'ANAMNESIS_ADD_FAMILY',
  DELETE_FAMILY: 'ANAMNESIS_DELETE_FAMILY',
  ADD_ALLERGY: 'ANAMNESIS_ADD_ALLERGY',
  DELETE_ALLERGY: 'ANAMNESIS_DELETE_ALLERGY',
  ADD_MEDICATION: 'ANAMNESIS_ADD_MEDICATION',
  DELETE_MEDICATION: 'ANAMNESIS_DELETE_MEDICATION',
  UPDATE_HABITS: 'ANAMNESIS_UPDATE_HABITS',
} as const;

export type AnamnesisPermission = (typeof ANAMNESIS_PERMISSIONS)[keyof typeof ANAMNESIS_PERMISSIONS];

export const TIMELINE_PERMISSIONS = {
  VIEW: 'TIMELINE_VIEW',
  CREATE: 'CLINICAL_SESSION_CREATE',
  VIEW_DETAIL: 'CLINICAL_SESSION_VIEW_DETAIL',
  UPDATE: 'CLINICAL_SESSION_UPDATE',
  DELETE: 'CLINICAL_SESSION_DELETE',
  UPLOAD_ATTACHMENT: 'CLINICAL_SESSION_UPLOAD_ATTACHMENT',
  VIEW_ATTACHMENTS: 'CLINICAL_SESSION_VIEW_ATTACHMENTS',
  DELETE_ATTACHMENT: 'CLINICAL_SESSION_DELETE_ATTACHMENT',
} as const;

export type TimelinePermission = (typeof TIMELINE_PERMISSIONS)[keyof typeof TIMELINE_PERMISSIONS];

export const ODONTOGRAM_PERMISSIONS = {
  VIEW: 'ODONTOGRAM_VIEW',
  NAVIGATE_HISTORY: 'ODONTOGRAM_NAVIGATE_HISTORY',
  START_SESSION: 'ODONTOGRAM_START_SESSION',
  MARK_CONDITIONS: 'ODONTOGRAM_MARK_CONDITIONS',
  CLEAR: 'ODONTOGRAM_CLEAR',
  REGISTER_SESSION: 'ODONTOGRAM_REGISTER_SESSION',
  TOGGLE_VIEW: 'ODONTOGRAM_TOGGLE_VIEW',
  UPLOAD_IMAGES: 'ODONTOGRAM_UPLOAD_IMAGES',
} as const;

export type OdontogramPermission = (typeof ODONTOGRAM_PERMISSIONS)[keyof typeof ODONTOGRAM_PERMISSIONS];

export const CLINICAL_DOCS_PERMISSIONS = {
  VIEW: 'CLINICAL_DOCS_VIEW',
  UPLOAD: 'CLINICAL_DOCS_UPLOAD',
  DELETE: 'CLINICAL_DOCS_DELETE',
  VIEW_ADVANCED: 'CLINICAL_DOCS_VIEW_ADVANCED',
} as const;

export type ClinicalDocsPermission = (typeof CLINICAL_DOCS_PERMISSIONS)[keyof typeof CLINICAL_DOCS_PERMISSIONS];

export const DICOM_PERMISSIONS = {
  VIEW_MENU: 'DICOM_VIEW_MENU',
  VIEW_LIST: 'DICOM_VIEW_LIST',
  VIEW_STUDY: 'DICOM_VIEW_STUDY',
  USE_MPR: 'DICOM_USE_MPR',
  USE_MEASUREMENTS: 'DICOM_USE_MEASUREMENTS',
  USE_WINDOW: 'DICOM_USE_WINDOW',
  ADD_ANNOTATIONS: 'DICOM_ADD_ANNOTATIONS',
  CHANGE_LAYOUT: 'DICOM_CHANGE_LAYOUT',
} as const;

export type DicomPermission = (typeof DICOM_PERMISSIONS)[keyof typeof DICOM_PERMISSIONS];
