export const API_ROUTES = {
    USERS_APPOINTMENTS: '/users_appointments',
    CALENDARS: '/calendars',
    SERVICES: '/services',
    USER_SERVICES: '/services/user_services',
    USERS: '/users',
    APPOINTMENTS_AVAILABILITY: '/appointments_availability',
    APPOINTMENTS_UPSERT: '/appointments/upsert',
    APPOINTMENTS_UPDATE_COLOR: '/appointments/update_color',
    APPOINTMENTS_DELETE: '/appointments/delete',
    ALERTS: '/alerts',
    APPOINTMENTS: '/appointments',
    CASHIER: {
        CASH_POINTS: '/cashier/cash-points',
        CASH_POINTS_SEARCH: '/cash_points/search',
        CASH_POINTS_UPSERT: '/cash_points/upsert',
        CASH_POINTS_DELETE: '/cash_points/delete',
        CASH_POINTS_STATUS: '/cash_points/status',
        MISCELLANEOUS_CATEGORIES: '/cashier/miscellaneous-categories',
        MISCELLANEOUS_CATEGORIES_GET: '/misc_categories',
        MISCELLANEOUS_CATEGORIES_UPSERT: '/misc_categories/upsert',
        MISCELLANEOUS_CATEGORIES_DELETE: '/misc_categories/delete',
        MISCELLANEOUS_TRANSACTIONS: '/cashier/miscellaneous-transactions',
        MISCELLANEOUS_TRANSACTIONS_GET: '/misc_transactions',
        MISCELLANEOUS_TRANSACTIONS_UPSERT: '/misc_transactions/upsert',
        MISCELLANEOUS_TRANSACTIONS_DELETE: '/misc_transactions/delete',
        PAYMENT_METHODS: '/metodospago/all',
        SESSIONS: '/cashier/sessions',
        SESSIONS_SEARCH: '/cash-session/search',
        SESSIONS_PRINT: '/cash-session/print',
        SESSIONS_ACTIVE: '/cash-session/active',
        SESSIONS_MOVEMENTS: '/cash-session/movements',
        SESSIONS_OPEN: '/cash-session/open',
        SESSIONS_OPEN_PRINT: '/cash-session/open/print',
        SESSIONS_CLOSE: '/cash-session/close',
        SESSIONS_CLOSE_PRINT: '/cash-session/close/print',
        SESSIONS_DECLARE: '/cash-session/declare',
        SESSIONS_PREFILL: '/cash-session/prefill',
        COTIZACIONES: '/cotizaciones',
    },
    CLINIC_CATALOG: {
        AILMENTS: '/clinic-catalog/ailments',
        DENTAL_CONDITIONS: '/clinic-catalog/dental-conditions',
        DENTAL_SURFACES: '/clinic-catalog/dental-surfaces',
        MEDICATIONS: '/clinic-catalog/medications',
    },
    CLINIC_HISTORY: '/clinic-history/:user_id',
    COMMUNICATIONS: {
        BASE: '/communications',
        CHANNELS: '/communications/channels',
    },
    CONFIG: {
        AVAILABILITY_EXCEPTIONS: '/config/availability-exceptions',
        CALENDARS: '/config/calendars',
        CLINICS: '/config/clinics',
        CURRENCIES: '/config/currencies',
        DOCTOR_AVAILABILITY: '/config/doctor-availability',
        DOCTORS: '/config/doctors',
        HOLIDAYS: '/config/holidays',
        SCHEDULES: '/config/schedules',
        SERVICES: '/config/services',
    },
    DASHBOARD: {
        SUMMARY: '/dashboard_summary',
        SALES_SUMMARY: '/dashboard_sales_summary',
        SALES_BY_SERVICE: '/dashboard_sales_by_service',
        INVOICE_STATUS: '/dashboard_invoice_status',
        NEW_VS_RECURRING_PATIENTS: '/dashboard_new_vs_recurring_patients',
    },
    LOGIN: '/login',
    ORDERS: '/orders',
    PERMISSIONS: '/permissions',
    PROVIDERS: '/providers',
    PURCHASES: {
        INVOICES: '/purchases/invoices',
        ORDERS: '/purchases/orders',
        PAYMENTS: '/purchases/payments',
        QUOTES: '/purchases/quotes',
        SERVICES: '/purchases/services',
    },
    QUOTES: '/quotes',
    RESET_PASSWORD: '/reset-password',
    ROLES: '/roles',
    SALES: {
        INVOICES: '/sales/invoices',
        ORDERS: '/sales/orders',
        PAYMENT_METHODS: '/sales/payment-methods',
        PAYMENTS: '/sales/payments',
        QUOTES: '/sales/quotes',
        SERVICES: '/sales/services',
    },
    SET_FIRST_PASSWORD: '/set-first-password',
    SHARED_STUDIES: '/shared-studies',
    STUDIES: '/studies',
    SYSTEM: {
        ACCESS: '/system/access',
        ALERT_CATEGORIES: '/system/alert-categories',
        ALERT_RULES: '/system/alert-rules',
        ALERTS_CONFIG: '/system/alerts-config',
        AUDIT: '/system/audit',
        COMMUNICATION_HISTORY: '/system/communication-history',
        COMMUNICATION_TEMPLATES: '/system/communication-templates',
        CONFIG: '/system/config',
        ERRORS: '/system/errors',
        EXECUTION_HISTORY: '/system/execution-history',
        USERS: '/system/users',
    },
};